name: "Release Workflow Agenda"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_release:
    name: Criar Release no GitHub
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Criar Release
        uses: softprops/action-gh-release@v1
        with:
          name: Versão ${{ github.ref_name }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Log de Sucesso
        run: |
          echo "✅ Release ${{ github.ref_name }} criada com sucesso!"